"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from environs import Env
import os
env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", default="dev-only-insecure-key-do-not-use-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

if not DEBUG and SECRET_KEY.startswith("dev-only"):
    raise ImproperlyConfigured("DEBUG=False bo'lganda SECRET_KEY .env da majburiy.")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])

# Custom user model
AUTH_USER_MODEL = 'users.CustomUser'

# Application definition

INSTALLED_APPS = [
    'unfold',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.gis',
    "users",
    "complaints",
    "common",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"
USER_MODEL = "users.CustomUser"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": env.str("DB_NAME"),
        "USER": env.str("DB_USER"),
        "PASSWORD": env.str("DB_PASSWORD"),
        "HOST": env.str("DB_HOST"),
        "PORT": env.str("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True



# Tasdiqlash kodini yuborish (SMTP). EMAIL_HOST_USER berilmasa, kod terminalga chiqadi (dasturlash rejimi).
EMAIL_HOST = env.str("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")
EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
    if EMAIL_HOST_USER
    else "django.core.mail.backends.console.EmailBackend"
)




LOGIN_REDIRECT_URL = '/login'
LOGOUT_REDIRECT_URL = '/logout'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "EkoMurojat Admin",
    "SITE_HEADER": "EkoMurojat Boshqaruv Paneli",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "🌿",
        "dark": lambda request: "🌿",
    },
    "SITE_LOGO": None,
    "SITE_SYMBOL": "🌿",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "config.settings.environment_callback",
    "DASHBOARD_CALLBACK": "config.settings.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "16 185 129",
            "700": "5 150 105",
            "800": "4 120 87",
            "900": "6 78 59",
            "950": "2 44 34",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "uz": "🇺🇿",
                "ru": "🇷🇺",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Asosiy",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Foydalanuvchilar",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Foydalanuvchilar",
                        "icon": "person",
                        "link": lambda request: "/admin/users/customuser/",
                    },
                ],
            },
            {
                "title": "Murojaatlar",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Murojaatlar",
                        "icon": "mail",
                        "link": lambda request: "/admin/complaints/complaint/",
                    },
                    {
                        "title": "Rasmlar",
                        "icon": "image",
                        "link": lambda request: "/admin/complaints/image/",
                    },
                ],
            },
            {
                "title": "Umumiy",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Viloyatlar",
                        "icon": "location_on",
                        "link": lambda request: "/admin/common/region/",
                    },
                    {
                        "title": "Tumanlar",
                        "icon": "place",
                        "link": lambda request: "/admin/common/district/",
                    },
                    {
                        "title": "Tashkilotlar",
                        "icon": "business",
                        "link": lambda request: "/admin/common/tashkilot/",
                    },
                ],
            },
        ],
    },
}

def environment_callback(request):
    """Environment badge for admin"""
    return ["Development", "warning"] if DEBUG else ["Production", "danger"]

def dashboard_callback(request, context):
    """Custom dashboard data"""
    return context
