# Generated by Django 6.0 on 2025-12-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori')], max_length=20, null=True, verbose_name='Muhimlik'),
        ),
    ]
