# Generated by Django 6.0 on 2025-12-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori')], default=None, max_length=20, null=True, verbose_name='Muhimlik'),
        ),
    ]
